- README.md
- changelogs/unreleased/-1wn3u3e.yml
- Added information in the readme regarding contribution and how to build the app
> Updated: the README file of the app(#1wn3u3e)

- src/views/OrderDetail.vue
> Added: text-wrap property(#1wuuacq)

- src/locales/en.json
- src/services/ShopifyService.ts
- src/views/Login.vue
- src/views/Shopify.vue
> Improved: code to get and use api key from environment variables (#1x633b0)

- changelogs/unreleased/-1x64ce8.yml
- src/views/Shopify.vue
> Improved install page logo and content (#1x64ce8)

- src/components/ProductListItem.vue
- src/locales/en.json
- src/services/StockService.ts
- src/store/index.ts
- src/store/modules/order/actions.ts
- src/store/modules/stock/StockState.ts
- src/store/modules/stock/actions.ts
- src/store/modules/stock/getters.ts
- src/store/modules/stock/index.ts
- src/store/modules/stock/mutation-types.ts
- src/store/modules/stock/mutations.ts
- src/views/OrderDetail.vue
- src/views/Settings.vue
> Added: stock store in the vuex modules and used the getters to display the inventory count(#1x640rx)

- src/store/modules/product/actions.ts
> Replaced: toast to console error statement(#1x640rx)

- src/App.vue
> Improved: code to prepare loader on app mounted and assign it to null on dismiss(#1x640rx)

- changelogs/unreleased/-1x640rx.yml
- src/components/OrderItemCard.vue
- src/store/modules/product/actions.ts
- src/views/OrderDetail.vue
- Currently, the order date is being display, so changed it display the time delta
- Improved code to prepare the payload for searchProducts API, as sometimes the payload is not prepared properly and thus  having an error response
Closes #
> Improved: code to display the time delta and solve the issue of payload not properly prepared for searchProducts API(#1x640rx)

- changelogs/unreleased/-1xhkqjh.yml
- src/locales/en.json
- src/views/OrderDetail.vue
> Removed some references of the reroute scenario(#1xhkqjh)

- changelogs/unreleased/-1xx2g9h.yml
- src/views/Orders.vue
> Improved card styling for desktop view of orders page (#1xx2g9h)

- src/components/OrderItemCard.vue
- src/views/OrderDetail.vue
> Added: if condition to only show order label when order id is available(#1ye5r94)

- src/views/Settings.vue
> Updated the markup #1y2ract

- changelogs/unreleased/-24bcp14.yml
- src/locales/en.json
- src/views/Orders.vue
Closes #
Added a badge based on the order status
After:
> Added: logic and styling to show the badge based on order status(#24bcp14)

- changelogs/unreleased/-21aqct8.yml
- src/views/Catalog.vue
- src/views/Login.vue
- src/views/Settings.vue
> Removed fullscreen=true from ion-content of all pages(#21aqct8)

- changelogs/unreleased/-22x7jng.yml
- src/views/Orders.vue
> Updated: title of orders page to facility name(#22x7jng)

- src/types/Order.ts
- src/types/Product.ts
- src/types/index.ts
> Added types

- changelogs/unreleased/-23ecz5d.yml
- src/views/Tabs.vue
> Improved styling of ion-tab-bar(#23ecz5d)

- public/index.html
> Added theme color in index.html file

- .eslintrc.js
- src/components/Image.vue
- src/store/modules/product/actions.ts
- src/store/modules/user/actions.ts
- src/views/Tabs.vue
> Fixed: build console warnings (#2d932bv)

- src/store/modules/user/actions.ts
> Fixed: the case when getting 404 for the getUserPreference api by handling the condition in try catch block(#2gnze24)

- .env.example
> Improved: env.example to enable packing slip option on test-hc instance(update-env)

- src/store/modules/order/actions.ts
Closes https://app.clickup.com/t/2hcqnu2
In rejectOrderItem, as we are creating a new ship group for rejected items when making concurrent API calls multiple records with same shipGroupSeqId is creating causing primary key constraint failure. Subsequent API calls should be done in sequence and not in parallel
> Fixed: Error when rejecting order with multiple items (#2hcqnu2)

- .github/PULL_REQUEST_TEMPLATE.md
Remove "important notice" from PR template
Closes #150 
> Remove important notice

- package-lock.json
- package.json
> Updated: app version to prepare for minor release

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for minor release(v2.2.0)

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for minor release

- src/views/Settings.vue
> Fixed: show packing slip toggle (#85zrphr3t)

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-release.yml
> Fixed: build failure due to node version 18 on github (#85zrmkx7q)

- src/views/ProductDetail.vue
> Fixed: warehouse should not be in other stores list (#1uvvc3x)

- src/store/modules/product/actions.ts
> Fixed: loader should be dismissed when API fails on catalog and product page

- src/views/Settings.vue
> Moved packing slip and shipping order configuration from oms to app settings(#85zrpq1yd)

- src/views/ProductDetail.vue
> Improved: selected color and size should not fetch variant info again

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for minor release(v2.5.0)

- src/store/modules/user/actions.ts
> Fixed: Duplicate facility in facility switcher(#85zrpubf1)

- package-lock.json
- package.json
> Updated: app version for minor release (2.6.0)

- package-lock.json
- package.json
- release-notes.md
> Updated: release notes for minor release(2.7.0)

- src/views/Orders.vue
> Changed the order of icons in packed section

- src/views/Orders.vue
Moved mail icon to far right and change to outline
> Changed the order of icons for sending

- src/store/modules/product/actions.ts
> Improved: search query by removing wildcards

- src/views/Settings.vue
Due to typo with variable name, facility not being changed
Closes #
> Fixed: facility not changed from the settings page

- package-lock.json
- package.json
Upgraded to latest oms-api package that allows setting response content type
Closes #
> Fixed: Packing slip not generated (#230)

- src/services/OrderService.ts
- src/views/OrderDetail.vue
> Updated: added customer email on order details page (#85zt94890)

- src/views/OrderDetail.vue
> Fixed: hasError import from utils

- package-lock.json
- package.json
- release-notes.md
> Updated: app version for minor release (2.12.0)

- src/views/ShipToStoreOrders.vue
> Fixed: show order name below customer name on ship to store orders (#248)

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-release.yml
- .github/workflows/pull-request.yml
> Implemented: updated actions to common workflow

- src/locales/ja.json
> Fixed: ja locale file to remove duplicate commas and added a missing comma

- package-lock.json
- package.json
> Updated: app version for minor release (2.14.0)

- package-lock.json
- package.json
> Updated: app version for minor release (2.15.0)

- src/views/Orders.vue
Related https://github.com/hotwax/bopis/pull/277
> Fixed: issue of facility name not visible on orders page(#277)

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-release.yml
Closes #
Improved: Passed firebase config secrets. In order to set the firebase config during auto-deploy.
> Improved: Passed firebase config secrets.

- package-lock.json
- package.json
> Updated: Used latest dxp-component version.

- package-lock.json
- package.json
- public/firebase-messaging-sw.js
Closes #
Updated: Used latest dxp-component version 1.7.5.
> Updated: Used latest dxp-component version 1.7.5.

- src/main.ts
> Improved: Added logs to print firebase config just to debug.

- .env.example
- src/main.ts
Closes #
Fixed: corrected env variable name to VUE_APP_FIREBASE_VAPID_KEY.
> Fixed: corrected env variable name.

- public/firebase-messaging-sw.js
Closes #
Improved: Corrected notification icon path.
> Improved: Corrected notification icon path.

- src/components/NotificationPreferenceModal.vue
- src/store/modules/user/actions.ts
- src/utils/firebase.ts
> Improved: used ofbizInstanceName for generating topic name for notifications

- src/components/ProductListItem.vue
- src/services/StockService.ts
- src/store/modules/product/actions.ts
- src/store/modules/stock/actions.ts
- src/store/modules/stock/getters.ts
> Implemented: code to display QOH instead of ATP (#308)

- package-lock.json
- package.json
Created a minor release (v2.16.0) for the app.
> Updated: package lock and package file for minor release(v2.16.0)

- package-lock.json
- package.json
Closes #
Updated: App version for the minor release (2.17.0).
> Updated: App version for the minor release (2.17.0).

- src/locales/en.json
- src/locales/es.json
- src/locales/ja.json
> Fixed: warning due to missing label entry

- src/router/index.ts
- src/views/Orders.vue
- src/views/Settings.vue
> Updated: UI to remove notifications button and preference from settings

- package-lock.json
- package.json
> Updated: app version for patch release (2.17.1)

- package-lock.json
- package.json
> Updated: version for DXP in package.json

- src/router/index.ts
- src/views/Orders.vue
- src/views/Settings.vue
> Reverted: commented UI for notifications

- src/main.ts
Fix for #312 
Removed the Unwanted Console statements
Closes #310
> Updated the main.ts file and removed the console statements for issue #310

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v2.18.0)

- src/locales/en.json
- src/views/OrderDetail.vue
> Fixed: 'cannot fulfill order' message on order details page (#338)

- src/views/OrderDetail.vue
> Fixed: issue of payment chip not visible on order detail page

- src/App.vue
> Fixed: issue of product identifier api fails as token is not set before fetching product identifier(#250)

- src/services/OrderService.ts
- src/store/modules/order/actions.ts
- src/utils/index.ts
- src/views/OrderDetail.vue
> Implemented: UI to show phone number and update payment status chip colour on order details page

- package-lock.json
- package.json
Closes #
Updated: App version for minor release(2.19.0).
> Updated: App version for minor release(2.19.0).

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (2.20.0).
> Updated: app version for the minor release (2.20.0).

- src/App.vue
> Reverted: "Fixed: not getting product identifiers on app refresh" commit

- src/services/UserService.ts
- src/store/modules/user/actions.ts
Closes #357
Implemented logic to check if enum exists for partial order rejection and create one if not exists.
> Fixed: Partial rejection setting not working due to no enum created (#357)

- package-lock.json
- package.json
> Updated: app version for minor release(2.21.0)

- src/store/modules/user/actions.ts
> Fixed: Permission issue when defining a base permission for app

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (v2.22.0).
> Updated: app version for the minor release (v2.22.0).

- src/main.ts
#354
- Added a entry in `main` file to fix html tags not working in the translations.
> Fixed: html tags not working in the translations (#354)

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v2.23.0)

- package-lock.json
- package.json
#400
Update the version of the dxp-component dependency.
> Improved: version of the dxp-component dependency (#400)

- package-lock.json
- package.json
#
Updated: app version for minor release v2.25.0
> Updated: app version for minor release v2.25.0

- package-lock.json
- package.json
> Updated: app version for the patch release (v2.25.1)

- package-lock.json
- package.json
> Updated: app version for the patch release(v2.26.1)

- package-lock.json
- package.json
> Updated: app version for the patch release (v2.26.2)

- src/components/EditPickerModal.vue
#444
Displayed ion spinner while fetching pickers on the edit picker modal.
> Implemented: spinner inside of the edit picker modal (#444)

- package-lock.json
- package.json
> Updated: app version for the patch release (v2.26.3)

- src/components/EditPickerModal.vue
- src/services/PicklistService.ts
- src/views/AssignPickerModal.vue
#447
- Migrated picker fetching logic to Solr 
- Added infinite scrolling in edit picker modal.
> Improved: migrated the picker fetching logic from performFind to Solr(#447)

- package-lock.json
- package.json
> Updated: app version for the patch release (v2.26.4)

- package-lock.json
- package.json
> Updated: app version for patch release v2.26.5

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-release.yml
#
Added prefix in the hotwax secrets used inside in the app workflow.
> Improved: added prefix to the firebase secrets so to handle dev deployment workflow

- package-lock.json
- package.json
> Updated: app version for patch release v2.26.6

- src/views/Settings.vue
https://github.com/hotwax/bopis/pull/425
- Updated the `@updateFacility` event binding in `<DxpFacilitySwitcher>` to pass the `updateFacility` function directly instead of invoking it with a parameter.
> Improved: Refactor <DxpFacilitySwitcher> event binding to directly pass updateFacility function(#dxp-288)

- src/components/ProductListItem.vue
#463 
#
Improved: Displayed badge for kit (#463).
> Improved: Displayed badge for kit (#463).

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v3.1.0)

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v3.2.0)

- .firebaserc
- firebase.json
#
As we are no more using multiple production instances of the app, thus removed the config entries for the same.
> Removed: unused hosting entries from the firebase config file

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v3.3.0)

- package-lock.json
- package.json
> Improved: package.json & package-lock.json for patch release to 3.3.1

- src/locales/en.json
- src/locales/ja.json
- src/views/OrderDetailUpdated.vue
> Improved: css to correctly display the kit components

- package-lock.json
- package.json
> Updated: app version for minor release v3.4.0

- src/utils/solrHelper.ts
#505 
#
user can now search for orders in completed tab using customer name.
> Improved: the search functionality, user can now search for orders in completed tab using customer name.(#505)

- src/components/ProductListItem.vue
https://github.com/hotwax/dxp-components/issues/362
#
> Improved: the field SHOPIFY_PROD_SKU has been deprecated thus removed it.

- package-lock.json
- package.json
- Updated the app version from 3.5.0 to 3.6.0 for minor release.
> Improved: app version in package and lock file for minor release(v3.6.0)

- package-lock.json
- package.json
- Updated the app version from 3.6.0 to 3.6.1 for patch release.
> Improved: app version in package & lock file for patch release(v3.6.1)

- src/components/EditPickerModal.vue
- src/views/AssignPickerModal.vue
https://github.com/hotwax/fulfillment/issues/975
> Improved: code to filter the pickers based on the status[enabled/disabled](fulfillment/975)

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v3.7.0)

- package-lock.json
- package.json
- Updated the app version from 3.7.0 to 3.7.1 for patch release.
> Improved: app version in package & lock file for patch release (v3.7.1)

- src/store/modules/order/actions.ts
- src/store/modules/product/actions.ts
- src/views/OrderDetailUpdated.vue
#536
- Kit product batch showing in case of other ship groups.
- Fixed kit not showing on order detail after page refresh.
> Improved: added support for kit component in other shipGroups in details page and fixed kits not showing on refresh (#536)

- package-lock.json
- package.json
> Updated: app version for patch release v3.7.4

- package-lock.json
- package.json
> Updated: app version for minor release v3.8.0

- src/store/modules/user/actions.ts
> Updated: the user profile before setting the ECom store preference(#568)

- src/views/OrderDetailUpdated.vue
- src/views/Orders.vue
> Updated the API call to print picklist first before packing the order(#568)

- src/components/RejectOrderItemModal.vue
- src/views/OrderDetailUpdated.vue
> Handled partial rejection case and correct UI display after successful rejection(#568)

- src/views/Orders.vue
> Fixed ready for pickup issue with missing shipmentId(#568)

- src/views/Settings.vue
> Fixed: go to oms button not working as its redirecting to moqui, removed usage of dxp oms component and define the UI in the app(#602)

- src/components/TimeZoneSwitcher.vue
- src/main.ts
- src/store/modules/user/actions.ts
- src/utils/index.ts
- src/views/Settings.vue
> Fixed: time zone swicther issue by removing the dxp time zone component and defined a local component for timezone support(#602)

- src/components/RejectOrderItemModal.vue
- src/views/OrderDetailUpdated.vue
- src/views/Orders.vue
#575 
The commit message in the below commit was mistakenly written incorrectly. This Pull Request corrects the intent and provides clarity about the actual change.
New Message: Added the new data-testid in bopis
> Added the data-testid(#575)

- package-lock.json
- package.json
> Updated: app version for major release v4.0.0

- package-lock.json
- package.json
> Updated: app version for minor release v4.1.0

- src/services/OrderService.ts
- src/store/modules/order/actions.ts
- src/views/Orders.vue
- src/views/Settings.vue
> Added: support to show shipping orders

- src/views/OrderDetailUpdated.vue
#640
- fixed Picker should be displayed after assigning and printing picklist.
> Fixed : fetched order details again after print picklist (#640)

- src/store/modules/order/actions.ts
- src/views/OrderDetailUpdated.vue
#652
- Added checks to show the message on ui on ready to pickup or handover on the basis of order type.
> Fixed : improved checks to show the message to details page on the basis of orderType (#652)

- package-lock.json
- package.json
#
Fixed: Upgraded oms-api to v1.25.2 in order to fix user associated facilities correctly.
> Fixed: Upgraded oms-api to v1.25.2 in order to fix user associated facilities correctly

- package-lock.json
- package.json
> Updated: app version for patch release v4.1.5

- package-lock.json
- package.json
#
Fixed: Upgraded oms-api to v1.25.3 in order to fetch admin facilities correctly.
> Fixed: Upgraded oms-api to v1.25.3 in order to fetch admin facilities correctly.

- package-lock.json
- package.json
> Updated: app version for patch release v4.1.6

- package-lock.json
- package.json
> Updated: app version for patch release v4.1.7
