hotwax/bopis

.gitignore
package-lock.json
package.json
src/router/index.ts
src/services/ShopifyService.ts
src/views/Shopify.vue

Implemented: use bopis app as shopify embedded app (#1x633b0)

---

changelogs/unreleased/-1uvvbc4.yml
src/router/index.ts
src/views/Catalog.vue
src/views/Tabs.vue

Implemented static UI for Catalog page(#1uvvbc4)

---

src/components/OrderItemCard.vue
src/components/ProductListItem.vue
src/locales/en.json
src/views/OrderDetail.vue
src/views/Settings.vue

Closes #
- Added prefix `Shopify order` on the order id.
- Removed extra space after the attributes names(Color and Size)
- Registered ion-note component as it was throwing a warning and improved indentation
Before:
After:

Made some minor improvements in the UI (#1ye5r94)

---

src/services/UserService.ts
src/store/modules/user/actions.ts

Closes #
https://github.com/hotwax/bopis/commit/380fc6655af64f21ee6d2e172672fecf59f9c9a6
Now we can store shipping order preference and later use it as per need

Implemented: Set and get the shipping order preference(#2g4w5hz)

---

src/store/modules/order/actions.ts

When rejecting order item from Bopis app using rejectOrderItem API, fulfillment status of item is not changed and there are duplicate entries created for the same with Cancelled and Cancelled + Rejected status.
Passed quantity as required for the rejectItem API for successful rejection
Closes https://app.clickup.com/t/2h1em69

Fixed: When rejecting order items duplicate entries are created and item is not rejected (#2h1em69)

---

src/components/ProductListItem.vue
src/views/OrderDetail.vue
src/views/Orders.vue

#113 
Closes #113 
In this MR, we have wrapped the text of product details 

Improved code by wrapping text on bopis order item details for products(#2h77kau)

---

src/views/Orders.vue

#114 
Closes #114 
**Before:**
**After:**

Improved markup and styling of segments in orders page(#2hcnrem)

---

src/store/modules/order/actions.ts
src/views/Orders.vue

Closes https://app.clickup.com/t/1zgmh46
When the order is marked ready to pickup/ship from open orders or ship/handover from packed orders, as the solr indexing takes some time and order is still in the list removed it locally and skipped any API calls

Fixed: Order is not removed after ready to pickup action  (#1zgmh46)

---

src/store/modules/order/actions.ts

Closes #
In rejectOrderItem, as we are creating a new ship group for rejected items when making concurrent API calls multiple records with the same shipGroupSeqId are created causing primary key constraint failure. Subsequent API calls should be done in sequence and not in parallel

Fixed: Error when rejecting order with multiple items (#2hcqnu2)

---

src/locales/en.json
src/views/Settings.vue

Updated: UI for shipping orders card on settings page (#85zrmkx7q)

---

src/authorization/Actions.ts
src/authorization/Rules.ts
src/views/Orders.vue

Implemented: disabling of buttons on orders page based on order update permission (#85zrthgeq)

---

src/store/modules/user/actions.ts
src/views/Settings.vue

1. Passed facilityId instead of currentFacility object for getting the product store
2. Used checked property for idientifying toggle value instad of value attribute
Closes #217

Fixed: Updating Delivery address permission for reroute fulfillment doesn't works  (#217)

---

src/views/Orders.vue

Closes #222 
Implemented rendering of packed orders based on ship group (order parts) in the UI. 
This fixed the issue of duplicate cards showing up vertically in the UI for orders having different ship groups.

Implemented: show order cards horizontally based on order ship group/part (#85zrv9fhc)

---

src/store/modules/order/actions.ts
src/views/OrderDetail.vue

Currently, if an order item is rejected from BOPIS app the item goes to brokering queue, but store pickup order should not be brokered to any location for fulfillment. Orders rejected in BOPIS app or store pickup orders should go to Store Pickup Rejected Queue.
Closes #251

Improved: Orders rejected in BOPIS app should go to Store Pickup Rejected Queue (#251)

---

src/views/Settings.vue
vue.config.js

Related Issue: https://github.com/hotwax/dxp-components/issues/177
Used the centralized oms instance navigator on the settings page which is implemented in dxp-components.

Implemented: centralized oms instance navigator in settings page from dxp-components (#177)

---

public/firebase-messaging-sw.js

Closes #
Fixed project ID missing error on login due to missing firebase config values in the firebase service worker file.

Fixed: firebase project ID error on login due to missing configs in firebase-messaging-sw

---

src/components/NotificationPreferenceModal.vue
src/store/modules/user/actions.ts
src/utils/firebase.ts
src/views/Settings.vue

Closes #
Improved: Updated occurrences of ofbizInstanceName with omsInstanceName(#301).

Improved: Updated occurrences of ofbizInstanceName with omsInstanceName(#301).

---

src/store/modules/stock/actions.ts
src/store/modules/stock/getters.ts
src/store/modules/stock/mutation-types.ts
src/store/modules/stock/mutations.ts

Fixed: support to display the stock for product as per the facility selected and removed unused mutations and types

---

src/store/modules/user/actions.ts

Closes #
Fetching product identifier on login fails as the token is not set, so moved the logic to fetch product identifier setting after token is updated in oms-api.

Fixed: issue of product identifier api fails as token is not set before fetching product identifier(#250)

---

src/App.vue

Closes #
Fixed issue of no order details showing on page refresh on details page and orders page. Fetched product identifier from app.vue for handling data loss on refresh.

Fixed: not getting product identifiers on app refresh resulting in no order details.

---

src/App.vue

Closes #
Added call to fetch product identifier inside app mounted hook and added check to make this call only when the token is available, as when login the mounted hook runs but we does not have token which results in api failure as unauthenticated and app logout and thus stucks in a loop

Fixed: product identifier not visible on refresh

---

package-lock.json
package.json
src/App.vue
src/components/EditPickerModal.vue
src/components/Image.vue
src/components/NotificationPreferenceModal.vue
src/logger/index.ts
src/main.ts
src/services/OrderService.ts
src/store/modules/order/actions.ts
src/store/modules/product/actions.ts
src/store/modules/stock/actions.ts
src/store/modules/user/actions.ts
src/store/modules/util/actions.ts
src/views/AssignPickerModal.vue
src/views/OrderDetail.vue
src/views/Orders.vue
src/views/ProductDetail.vue
src/views/Settings.vue
src/views/ShipToStoreOrders.vue

Closes #365
Added vue-logger-plugin dependency and use logger instead of console for errors.

Implemented: logger using vue logger plugin (#365)

---

src/views/AssignPickerModal.vue
src/views/Catalog.vue
src/views/Orders.vue
src/views/ShipToStoreOrders.vue

https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Fixed: infinite scroll issue when used with searchbar(dxp-289) 

---

src/views/AssignPickerModal.vue
src/views/Catalog.vue
src/views/Orders.vue
src/views/ShipToStoreOrders.vue

https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Fixed: Infinite scroll with searchbar and loading bug

---

src/components/EditPickerModal.vue
src/views/AssignPickerModal.vue

#389 
- Update the `payload` of the function which is responsible for searching.
- Added properties related to `group` and mention the number of fields in which the searching should perform.

Fixed: Allowed search on groupName to handle the case where picker is a party group(#389)

---

src/store/modules/user/index.ts
src/store/modules/user/mutations.ts

#395
- Clearing preference state on logout.
- Made showShippingOrder to false by default.

Improved: clearing user preference state on logout, showShippingOrder set to false by default (#395)

---

src/components/ProductListItem.vue
src/store/modules/order/actions.ts
src/views/OrderDetail.vue

#396
Displayed inventory computation for the items in other shipments of an order.

Improved: logic to show inventory computation of other shipment items in an order (#396)

---

src/store/modules/order/actions.ts

#403
Improved logic to appending isFetchingStock by default to false in all shipGroup items

Improved: logic to append isFetchingStock to false by default in shipGroup items (#403)

---

src/store/modules/user/actions.ts
src/views/Settings.vue

#405
Improved notification preferences updation logic so as to change toggle state only if preference updates successfully.

Improved: changing the state of notification preference toggle only if api success (#405)

---

src/views/Orders.vue

#416 
- When an `ion-item` element is added inside an ion-card, it creates a new layer on top of the card, and by default, the ion-item element has a background colour that covers the card, making it appear as though the ripple effect is not covering the entire card.
- Setting the background colour of the ion-item element to `transparent` within the ion-card allows the ripple effect to be visible underneath, creating the desired effect on the entire card.
- I took the reference from this github issue : https://github.com/ionic-team/ionic-framework/issues/21210
[3fb32fa5-12c7-46cd-9256-59a1ae71e337.webm](https://github.com/user-attachments/assets/a7cb5e01-7368-4587-b09e-a178e09d9aba)

Improved: ripple effect now show on the entire ion-card(#416)

---

src/locales/ja.json
src/store/modules/order/actions.ts
src/utils/order.ts
src/views/OrderDetail.vue

#410 
- Improved check when deriving status for shipGroup
- Added support to derive status for non pickup orders as well

Improved: logic to calculate derived status for order ship group and added check for displaying pending allocation as default category(#410)

---

src/locales/en.json
src/locales/es.json
src/locales/ja.json
src/services/OrderService.ts
src/store/modules/order/actions.ts
src/store/modules/user/getters.ts
src/store/modules/user/index.ts
src/store/modules/user/mutations.ts
src/utils/index.ts
src/views/AssignPickerModal.vue
src/views/OrderDetail.vue
src/views/Orders.vue
src/views/Settings.vue

#415
- Implemented logic to manage user preference for print picklist preference from settings page.
- Added support for the option to print picklists for open orders.

Implemented: support for print picklist in open orders (#415)

---

src/services/UserService.ts
src/views/OrderDetail.vue
src/views/Orders.vue

#430
Added handling for order with already created picklist in order details page.

Improved: added handling on order details page for the order with picklist already created (#430)

---

src/services/UserService.ts
src/views/Orders.vue

#428
- Added support for the picker role creation if not exists
- Fixed issue in assignPicker modal if closing without saving.

Improved: support for adding picker role to _NA_ party and fixed issue in assignPicker modal (#428)

---

src/locales/en.json
src/locales/es.json
src/locales/ja.json
src/views/AssignPickerModal.vue

#444
Displaying spinner while api for fetching pickers is in progress for better user experience.

Improved: showing ion spinner until picker list is being fetched (#444)

---

src/views/AssignPickerModal.vue

#444
Not showing spinner while fethcing picker using infinite scroll.

Fixed: stopped spinner to show on infinite scrolling (#444)

---

src/components/OrderItemRejHistoryModal.vue
src/components/RejectOrderModal.vue
src/components/ReportAnIssueModal.vue
src/store/modules/util/actions.ts

#438
Showing all rejection reasons only if user is admin else showing only the reasons from the bopis group.

Improved: logic to show rejection reason options based on admin permission (#438)

---

src/store/modules/user/actions.ts
src/views/Settings.vue

#459 
#
Fixed: Removed default setting creation from the BOPIS app to prevent duplicate settings (#459).
Here are the settings - 'ENABLE_TRACKING', 'PRINT_PACKING_SLIPS', 'PRINT_PICKLISTS', 'SHOW_SHIPPING_ORDERS'

Fixed: Removed default setting creation from the BOPIS app to prevent duplicate settings (#459).

---

src/views/Orders.vue

#468
- Added support to fetch the updated inventory of the item in the order.
- It only runs when the user has already checked the QOH on any of the tabs from "Open" and "Packed."
- If the user directly checks the inventory on the "Completed" tab, it will show the updated inventory of the item.

Improved: Added support for fetching the updated inventory in the Completed tab after the handover or ship of an order (#468)

---

src/views/Tabs.vue

#
Replaced settings icon with settingsOutline icon for consistency
Before:
After:

Improved: settings page icon in tabbar to use outline type icon

---

src/services/UserService.ts
src/store/modules/user/actions.ts

#482 
Removing duplicate code improves maintainability, readability, and reduces the risk of errors by making the code more concise and easier to modify.
Improved the code by removing duplicate method isEnumExists and createEnumeration in UserService and updated the related code accordingly

Improved: Code by removing duplicate method isEnumExists and createEnumeration in UserService and updated the related code accordingly.(#482)

---

src/views/Catalog.vue

#469 
Displayed parent product name on product find page instead of the primary and secondary identifier.

Improved: Displayed parent product name on product find page instead of the primary and secondary identifier.(#469)

---

src/services/UserService.ts

#
When fetching product stores for facility we are also fetching those stores which are already unlinked from the facility, resulting in wrong store preference data being fetched, so added check to filter the records by date, also added check to only fetch unique records.

Improved: code to not fetch the unlinked product stores for facility and only fetch unique product stores

---

src/store/modules/user/actions.ts
src/views/Settings.vue

#500 
- Added the call to update the reroute fulfillment configuration when updating the facility and also handled the case when it has no configuration or when the API fails.
- Added the action call for updating the partial order rejection configuration on facility change.

Fixed: On updating the facility, the settings related to the facility are also being updated (#500)

---

src/store/modules/order/actions.ts

#516 
- Added if condition to check the orderId in the updateCurrentItemGCActivationDetails action after you activate the gift card.

Improved: updated updateCurrentItemGCActivationDetails action logic (#516)

---

src/services/OrderService.ts

#516
- Set the viewSize to 250 when fetching gift card activation info for an order

Improved: Set the viewSize to 250 when fetching gift card activation info for an order (#516)

---

src/components/ConfirmCancelModal.vue

The last item in the cancellation summary modal in packed order details page now has full lines. (#521)

---

src/components/ProductListItem.vue
src/store/modules/order/actions.ts

#530 
- Updated the check for fetching activation card information on the "Completed" tab.  
- Also, in case of pagination, maintained the consistency of the completed orders list after fetching the order list.

Improved: added gift card related checks for completed tab (#530)

---

src/store/modules/user/actions.ts

#
Improved: Used OMS_FULFILLMENT_GROUP instead of PICKUP group checks during login to the BOPIS app (#545)

Improved: Used OMS_FULFILLMENT_GROUP instead of PICKUP group checks during login to the BOPIS app (#545)

---

src/store/modules/order/actions.ts
src/views/OrderDetailUpdated.vue

#541
- Made print picklist button in order detail product store setting driven
- Fixed assign modal opening even if picklist already created

Improved: made print picklist button in order detail product store setting driven, fixed assign modal opening even if picklist already created (#541)

---

src/services/OrderService.ts
src/views/OrderDetailUpdated.vue

Added functionality to reject bopis order item via rejectOrderItems instead of rejectOrderItem.
#577

Added functionality to reject bopis order item via rejectOrderItems instead of rejectOrderItem.

---

package-lock.json
package.json

#
As we have removed code for fetching api_key for moqui first app, so need to use the updated oms-api package to not add api_key in headers and just use the JWT auth code for authorization.

Improved: oms-api package version for fixing the auth headers issue

---

src/store/modules/order/actions.ts
src/views/Catalog.vue
src/views/Orders.vue
src/views/Settings.vue

#454 
- Added check to get the order type from state and set the same as selected segment so user lands on the segment in which the order belongs.

Fixed: issue of wrong segment being selected when coming from the details page to list page after refresh(#454)

---

src/store/modules/order/actions.ts
src/views/OrderDetailUpdated.vue

#640
- Fixed picker Not Displayed After Assigning And Printing Picklist On  Detail Page.

Fixed : Picker Not Displayed After Assigning And Printing Picklist On  Detail Page (#640)

---

src/store/modules/order/actions.ts
src/views/AssignPickerModal.vue

#640 
#
Fixed: Displayed associated picker correctly (#640).

Fixed: Displayed associated picker correctly (#640).

---

src/components/TimeZoneSwitcher.vue
src/main.ts
src/services/UserService.ts
src/store/modules/user/actions.ts
src/utils/index.ts
src/views/OrderDetailUpdated.vue
src/views/Settings.vue

Reverted the change made in 635, initally handled in 607
Reverted as we do not have full support of using dxp component in moqui first apps
#

Improved: flow to use the local timezone switcher component and removed usage of Dxp component and fix wrong rejection history after page refresh
